/// Represents the final adaptive decision returned by the library.
///
/// This object is produced by the runtime decision engine after:
/// - mapping learner telemetry into deployment-facing RL state
/// - performing policy lookup
/// - or applying deterministic fallback logic
class AdaptiveDecision {
  /// Creates an immutable adaptive decision.
  const AdaptiveDecision({
    required this.nextDifficulty,
    required this.reason,
    this.supportStrategy,
    this.sourceActionName,
    this.lookupKey,
    this.foundExactMatch = true,
  });

  /// Recommended next difficulty level.
  ///
  /// Typical values:
  /// - `veryEasy`
  /// - `easy`
  /// - `medium`
  /// - `hard`
  /// - `veryHard`
  final String nextDifficulty;

  /// Human-readable explanation from policy lookup or fallback logic.
  final String reason;

  /// Optional support/intervention label from exported decision metadata.
  ///
  /// Examples:
  /// - `recovery_support`
  /// - `flow_alignment`
  /// - `motivation_support`
  final String? supportStrategy;

  /// Optional original training-time action label.
  ///
  /// Examples:
  /// - `rest`
  /// - `medium_task`
  /// - `flow_task`
  final String? sourceActionName;

  /// Optional lookup key used during policy retrieval.
  final String? lookupKey;

  /// Whether the runtime decision came from an exact policy-table match.
  ///
  /// If `false`, the decision was generated by deterministic fallback logic.
  final bool foundExactMatch;

  /// Converts the decision to a serializable map.
  Map<String, dynamic> toMap() => {
    'nextDifficulty': nextDifficulty,
    'reason': reason,
    'supportStrategy': supportStrategy,
    'sourceActionName': sourceActionName,
    'lookupKey': lookupKey,
    'foundExactMatch': foundExactMatch,
  };

  /// Returns a copy of this decision with selected fields replaced.
  AdaptiveDecision copyWith({
    String? nextDifficulty,
    String? reason,
    String? supportStrategy,
    String? sourceActionName,
    String? lookupKey,
    bool? foundExactMatch,
  }) {
    return AdaptiveDecision(
      nextDifficulty: nextDifficulty ?? this.nextDifficulty,
      reason: reason ?? this.reason,
      supportStrategy: supportStrategy ?? this.supportStrategy,
      sourceActionName: sourceActionName ?? this.sourceActionName,
      lookupKey: lookupKey ?? this.lookupKey,
      foundExactMatch: foundExactMatch ?? this.foundExactMatch,
    );
  }

  @override
  String toString() {
    return 'AdaptiveDecision('
        'next=$nextDifficulty, '
        'reason=$reason, '
        'supportStrategy=$supportStrategy, '
        'sourceActionName=$sourceActionName, '
        'lookupKey=$lookupKey, '
        'foundExactMatch=$foundExactMatch'
        ')';
  }
}